##################通用配置##########################
spring:
  profiles:
    active: dev
    ##配置国际化
  messages:
    basename: i18n/messages
    encoding: UTF-8
    cacheSeconds: 5000

service:
  name: meeting-ecm