# Server config
server:
  port: 8084

logging:
    path: ../logs

scheduler:
  file: scheduler.xml

spring:
  redis:
      hostName: 10.95.121.181
      port: 6379
      password: camelot123
      pool:
        maxActive: 100
        maxWait: -1
        maxIdle: 10
        minIdle: 10
      timeout: 10000